version: "3"

vars:
  BINARY_NAME: desktop-automation
  MAIN_PATH: ./cmd/desktop-automation
  BUILD_DIR: ./bin

tasks:
  build:
    desc: Build the desktop automation CLI
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  run:
    desc: Run the desktop automation CLI
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}} {{.CLI_ARGS}}"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - go clean

  test:
    desc: Run tests
    cmds:
      - go test ./...

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  mod:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  default:
    desc: Show available tasks
    cmds:
      - go-task --list
